is_debug: true
listen:
  type: port
  bind_ip: localhost
  port: 8081
mongodb:
  host: localhost
  port: 27017
  username: testadm
  password: testadm
  auth_db: admin
  database: user_game_api
  collection_users: users
  collection_user_games: user_games